# Generated by Django 5.0.6 on 2024-06-24 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sterilization_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sterilization_process.material')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sterilization_process.sterilizationstage')),
            ],
        ),
    ]
